@startuml
skinparam classAttributeIconSize 0
hide circle

abstract class "{abstract}\nCommand" as Command {
    {abstract} +execute()
}

enum RecordType <<enumeration>> {
    EXPENSE
    LOAN
    SAVING
}

class AddCommand {
    {static} #COMMAND_ADD: String
    -amount: BigDecimal
    -issueDate: LocalDate
    -description: String
    -borrowerName: String
    -recordType: RecordType
    +AddCommand(:ArrayList<String>)
    +execute()
}

note right of Command::execute
    Parameters omitted for brevity.
end note

Command <|-- AddCommand

hide RecordType empty members
Command -left[hidden] RecordType

note "Other child Command objects omitted for brevity.\nPrivate methods are omitted." as N1

@enduml