@startuml
participant ModuleInfo
activate ModuleInfo
ModuleInfo -> ModuleInfo++ :  addReview
    alt ModuleInfo.modules.isEmpty()
        ModuleInfo -> Logger++ : log(Level.INFO, emptyListMessage)
        return

    else !ModuleInfo.modules.isEmpty()
        ModuleInfo -> ModuleInfo++ : viewAllModules()
        return
        ModuleInfo -> Ui++ : readCommandToInt()
        return moduleNumber
        alt isValid(moduleNumber)
            ModuleInfo -> ModuleInfo++ : printAlreadyAddedReviewMessage(module)
                opt module.review != emptyReviewString
                    ModuleInfo -> Module++ : getReview()
                    return
                    ModuleInfo -> Logger++ : log(Level.WARNING, deleteReviewWarningMessage)
                    return
                    ModuleInfo -> Ui++ : readCommand()
                    return YesOrNoToReplaceReview
                end
                ModuleInfo -> ModuleInfo++ : readReview()
                    loop !input.contains("/end")
                        ModuleInfo -> String++ : append(input)
                    return reviewString
                return reviewString
                alt !reviewString.isEmpty()
                    ModuleInfo -> ModuleInfo++ : printReviewAddedMessage(reviewString)
                    return reviewString
                end
            return reviewString
            ModuleInfo -> Module++ : setReview(reviewString)
            return
        end
        else !isValid(moduleNumber)
            ModuleInfo -> Ui++ : printInvalidIntegerMessage()
            return
        end
    end
return
@enduml