@startuml Add_Sequence_Diagram
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml
skinparam style strictuml

participant Ui #Turquoise
participant Parser #PaleGreen
participant Commands #PaleGreen
participant ReviewList #Gold
participant RecommendationList #Gold

activate Ui #Turquoise
Ui -> Parser : determineCommand()
activate Parser #PaleGreen

Parser -> Commands : add()
activate Commands #PaleGreen
    Commands -> RecommendationList : addRecommendation()
    activate RecommendationList #Gold
     activate ReviewList #Gold

        RecommendationList-> ReviewList: checkAndPrintDuplicateReview()

     deactivate ReviewList

    break DuplicateException
        RecommendationList --> Ui : printNoUniqueTitleMessage()
    end

    break EmptyInputException
        RecommendationList --> Ui : printEmptyInputMessage()
    end
        RecommendationList -> RecommendationList : add Recommendation

RecommendationList --> Commands
deactivate RecommendationList


Commands --> Parser
deactivate Commands
Parser --> Ui
deactivate Parser

@enduml