@startuml Add_Sequence_Diagram
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml
skinparam style strictuml

activate Ui
Ui -> Parser : determineCommand()
activate Parser

Parser -> Commands : add()
activate Commands

alt isReviewMode
    Commands -> ReviewList : addReview(input)
    activate ReviewList

    alt quick review
        ReviewList -> ReviewList : addQuickReview()

    else full review
        ReviewList -> ReviewList : addFullReview()

    else else
        ReviewList --> Ui : invalidCommand()
    end
    ReviewList --> Commands
    deactivate ReviewList

else !isReviewMode
    Commands -> RecommendationList : addRecommendation()
    activate RecommendationList

    RecommendationList -> RecommendationList : add Recommendation

    break DuplicateException
        RecommendationList --> Ui : printNoUniqueTitleMessage()
    end

    break EmptyInputException
        RecommendationList --> Ui : printEmptyInputMessage()
    end

RecommendationList --> Commands
deactivate RecommendationList

end
Commands --> Parser
deactivate Commands
Parser --> Ui
deactivate Parser

@enduml