@startuml
participant Duke
Duke -> Links : execute()
activate Links
Links -> Ui : readCommand()
activate Ui
Ui --> Links : command
deactivate Ui
Links -> ZoomLinkInfo : addZoomLink()
activate ZoomLinkInfo
ZoomLinkInfo -> Ui : printEnterRequirePassword
activate Ui
Ui -> Ui : readCommand
activate Ui
deactivate Ui
Ui --> ZoomLinkInfo :  passwordCommand
deactivate Ui
ZoomLinkInfo -> Ui : printEnterPassword()
activate Ui
Ui -> Ui : readCommand
activate Ui
deactivate Ui
Ui --> ZoomLinkInfo : password
deactivate Ui
ZoomLinkInfo -> ModuleInfo : getModule()
activate ModuleInfo
ModuleInfo --> ZoomLinkInfo : module
deactivate ModuleInfo
ZoomLinkInfo --> Module : setZoomLink()
activate Module
Module --> ZoomLinkInfo
deactivate Module
ZoomLinkInfo --> Links
deactivate ZoomLinkInfo

return
@enduml