@startuml ArchitectureDiagram
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class FridgeFriend FRIDGEFRIEND_COLOR
    Class Utilities UTILITIES_COLOR
    Class Exception EXCEPTION_COLOR
    Class Command COMMAND_COLOR
    Class Food FOOD_COLOR
}

Class "<$user>" as User FOOD_COLOR_T2
Class "<$documents>" as File UTILITIES_COLOR_T1


FridgeFriend -> Utilities
Utilities -[UTILITIES_COLOR_T3]--> Command
Food -[FOOD_COLOR_T3]-> Utilities
Command -[COMMAND_COLOR_T3]-> Food  
Command -[COMMAND_COLOR_T3]-> FridgeFriend
Command -[COMMAND_COLOR_T3]> Exception
Exception -[EXCEPTION_COLOR_T3]> Utilities
Utilities .right[UTILITIES_COLOR_T3].>File
User ..> Utilities

@enduml