@startuml Class_Diagram
hide circle
!define LIGHTGREEN
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml
skinparam classAttributeIconSize 0

together {
    class Ui
    class Parser
    class Commands
}

together {
    class RecommendationList
    class ReviewList
}

together {
    class Sorter
    class SortMethod
}

class Ui #Turquoise {
    + readCommand() : String
}

class Commands #PaleGreen {
    - boolean isReviewMode
}

class RecommendationList #Gold {
    - ui : Ui
    + recommendations : ArrayList<Recommendation>
    + addRecommendation()
    + listRecommendations()
    + editRecommendation()
    + deleteRecommendation()
    + convertRecommendation()
}

class ReviewList #Gold {
    - ui : Ui
    + reviews : ArrayList<Reviews>
    - displayStars : boolean
    + addReview()
    + sortReviews()
    + listReviews()
    + viewReview()
    + editReview()
    + deleteReview()
    + changeDisplay(displayType : String)
}

class Parser #PaleGreen {
    + determineCommand(input : String)
}

class Sorter #NavajoWhite {
    + sortMethod : SortMethod
    + stringToSortMethod(sortMethod : String) : SortMethod
    + sortMethodToString(sortMethod : SortMethod) : String
    + getSortMethod() : String
    + changeSortMethod(sortMethod : String)
    + sortReviews(reviewList : ArrayList) : ArrayList
}

class Storage #PowderBlue {
    - Ui ui
    + retrieveDataFile() : boolean
    + loadConnoisseurData() : ConnoisseurData
    + saveConnoisseurData()
}

enum SortMethod #NavajoWhite {
    RATING
    CATEGORY
    TITLE
    LATEST
    EARLIEST
}

Ui - Parser : parse commands >
Parser - Commands : execute commands >
Commands -- Storage : store data >
Commands -- ReviewList : execute on >
Commands -- RecommendationList : execute on >
RecommendationList - ReviewList : convert to >
ReviewList -- Sorter : sort using >
Sorter -- SortMethod

@enduml
