@startuml
'https://plantuml.com/sequence-diagram
hide footbox
activate ":HdBuy"
":HdBuy" -> ":CloseCommand": execute()
        activate ":CloseCommand"
        ":CloseCommand" -> ":TextUi": showExit()
        activate ":TextUi"
        ":CloseCommand" <-- ":TextUi"
        deactivate ":TextUi"
        ":HdBuy" <-- ":CloseCommand": signals imminent exit
        destroy ":CloseCommand"
@enduml