@startuml
skinparam classAttributeIconSize 0
hide circle

note "Other child Command objects omitted for brevity.\nPrivate methods are omitted." as N1

abstract class "{abstract}\nCommand" as Command {
    {abstract} +execute()
}

enum RecordType <<enumeration>> {
    EXPENSE
    LOAN
    SAVING
}

class AddCommand {
    {static} #COMMAND_ADD: String
    -amount: BigDecimal
    -issueDate: LocalDate
    -description: String
    -borrowerName: String
    -recordType: RecordType
    +AddCommand(:ArrayList<String>)
    +execute()
}

skinparam linetype polyline

Command <|-- AddCommand

hide RecordType empty members
Command -right[hidden] RecordType

@enduml