@startuml
skinparam classAttributeIconSize 0
hide circle

class CommandHandler {
    -isExit : boolean
    +CommandHandler()
    +isExit() : boolean
    +setExit(:boolean)
    +parseCommand(:ArrayList<String>, :RecordList): Command
    -createCommand(:ArrayList<String>, :RecordList): Command
}

class Finux {

}

CommandHandler"1" <-- Finux

@enduml