@startuml
!include style.puml
Participant ":CreditScoreCommand" as CreditScoreCommand
Participant ":Loan" as Loan
Participant ":Ui" as Ui
Participant ":RecordList" as RecordList
Participant ":CreditScoreReturnedLoansMap" as CreditScoreReturnedLoansMap

[-> CreditScoreCommand: execute()
activate CreditScoreCommand
CreditScoreCommand -> CreditScoreReturnedLoansMap : getCreditScoreOf(borrowerName : String)
activate CreditScoreReturnedLoansMap
CreditScoreReturnedLoansMap --> CreditScoreCommand : creditScore : int
deactivate CreditScoreReturnedLoansMap

loop For each record at index i
    CreditScoreCommand -> RecordList : getRecordAt(i : int)
    activate RecordList
    RecordList --> CreditScoreCommand : record : Record
    deactivate RecordList
    opt record is a Loan
        CreditScoreCommand -> Loan : getBorrowerName()
        activate Loan
        Loan --> CreditScoreCommand : :String
        CreditScoreCommand -> Loan : isReturn()
        Loan --> CreditScoreCommand : :boolean
        opt loaned to current borrower and not returned
            ref over CreditScoreCommand, Loan : Re-compute creditScore
        end
        Loan -[hidden]-> CreditScoreCommand
        deactivate Loan
    end
end
CreditScoreCommand -> Ui : printMessage()
activate Ui
Ui --> CreditScoreCommand
deactivate Ui
[<-- CreditScoreCommand
deactivate CreditScoreCommand

@enduml