@startuml

activate ":Duke"
":Duke" -> ":TaskManager"++ : execute

loop true

":TaskManager" -> ":Ui"++ : printTaskManagerMenu
return
":TaskManager" -> ":Ui"++ : readCommand
return

alt Integer.parseInt(command)
    opt command.equals(EXIT_COMMAND)
    ":TaskManager" --> ":Duke"
    end

":TaskManager" -> ":TaskManager"++ : deleteTask
":TaskManager" -> ":Ui"++ : printDeleteTaskMenu
return
":TaskManager" -> ":TaskManager"++ : getTaskNumber
return
":TaskManager" -> ":DeleteTask"++ : execute
    opt TaskManager.taskListIsEmpty(taskTypeNumber)
    ":DeleteTask" -> ":Ui"++ : printTaskListIsEmptyMessage
    return
    ":DeleteTask" --> ":TaskManager"
    end
    ":DeleteTask" -> ":Ui"++ : printSelectTaskNumberToDelete
    return
    alt DELETE_TASK
    ":DeleteTask" -> ":DeleteTask"++ : findAndDeleteTask
    return
    else DELETE_ASSIGNMENT
    ":DeleteTask" -> ":DeleteTask"++ : findAndDeleteAssignment
    return
    else DELETE_MIDTERM
    ":DeleteTask" -> ":DeleteTask"++ : findAndDeleteMidterm
    return
    else DELETE_FINAL_EXAM
    ":DeleteTask" -> ":DeleteTask"++ : findAndDeleteFinalExam
    return
    else default
    ":DeleteTask" -> ":Ui"++ : printInvalidIntegerMessage
    return
    end

else NumberFormatException
":DeleteTask" -> ":Ui"++ : printInvalidIntegerMessage
return

else IndexOutOfBoundsException
":DeleteTask" -> ":Ui"++ : printInvalidTaskNumberMessage
return
end

return
return

alt
":TaskManager" -> ":Storage"++ : saveAllFiles
return
else IOException
":TaskManager" -> ":Ui"++ : printFilesCouldNotBeSavedMessage
return
end

return

end

@enduml