@startuml
hide members
hide circle
skinparam classAttributeIconSize 0
package logic{
Class "{abstract}\nCommand" as Command
package doctorappointment {
Command <|-- ABCCommand
note right: ABCCommand = DoctorAppointmentAddCommand, \n DoctorAppointmentDeleteCommand,\n DoctorAppointmentHelpCommand,\n DoctorAppointmentListCommand, \n DoctorAppointmentReturnCommand
}
}
@enduml