@startuml
hide members
hide circle

package "Cap Simulator" {

}

package Task {
    package command {
        Class AddTask
        Class DeleteTask
        Class MarkOrUnmarkTask
        Class PinTask
    }
    Class TaskManager
    command -- TaskManager
    tasktypes <-- TaskManager
    package tasktypes {
            Class Assignment
            Class FinalExam
            Class Midterm
            Class Task

            Assignment --|> Task
            Midterm --|> Task
            FinalExam --|> Task
        }
}

package Link {
  Class ExternalLinks
  Class LinkInfo
  Class Links
  Class ZoomLinkInfo

ExternalLinks --|> Links
}

package Module_Info {
    Class ModuleInfo
    Class Module
    Class Component

    ModuleInfo -> Module
    ModuleInfo -> Task
    ModuleInfo -> ZoomLinkInfo
}


@enduml