@startuml
'https://plantuml.com/sequence-diagram
hide footbox
activate ":HdBuy"
":HdBuy" -> ":HelpCommand": execute()
        activate ":HelpCommand"
        ":HelpCommand" -> ":TextUi": showHelp()
        activate ":TextUi"
        ":HelpCommand" <-- ":TextUi"
        deactivate ":TextUi"
        ":HdBuy" <-- ":HelpCommand"
        destroy ":HelpCommand"
@enduml