@startuml
'https://plantuml.com/sequence-diagram

activate ":HdBuy"
":HdBuy" -> ":ListCommand": execute()
        activate ":ListCommand"
        ":ListCommand" -> ":TextUi": showParameters(userInputs)
        activate ":TextUi"
        ":ListCommand" <-- ":TextUi"
        deactivate ":TextUi"
        ":HdBuy" <-- ":ListCommand"
        destroy ":ListCommand"
@enduml