@startuml ListCommandSequenceDiagram
'https://plantuml.com/sequence-diagram

!include style.puml

box "Command\n" COMMAND_COLOR_T1
Participant ":ListCommand" as list COMMAND_COLOR
end box

box "Food\n" FOOD_COLOR_T1
Participant ":Fridge" as fridge FOOD_COLOR
Participant ":Food" as food FOOD_COLOR
end box

autoactivate on
-> list: execute()

list -> list: getListAllMessage()
loop food in fridge
    list-> fridge: getFoodDescription()

    fridge -> food: getFood()
        return
        return

    list --> list: list of all Food
end
return
@enduml