@startuml

hide members
hide circle
skinparam classAttributeIconSize 0
package logic{
package command{
Class "{abstract}\nCommand" as Command
package doctorappointment {
Command <|-- ABCCommand
}
package inventory {
Command <|-- DEFCommand
}
package nurseschedule {
Command <|-- GHICommand
}
package patient {
Command <|-- JKLCommand
}
package staff {
Command <|-- MNOCommand
}
package startmenu {
Command <|-- PQRCommand
}
}
package errorchecker{
Class XYZChecker
note right: XYZChecker = DoctorAppointmentChecker, \n InventoryChecker, \n MainChecker, \n NurseScheduleChecker, \n PatientChecker, \n StaffChecker
}

package parser{
Class PQRParser
note right: PQRParser = DoctorAppointmentParser, \n InventoryParser, \n NurseScheduleParser, \n PatientParser, \n StaffParser, \n StartMenuParser
PQRParser .down.> XYZChecker : creates >
PQRParser .up.> ABCCommand : creates >
PQRParser .up.> DEFCommand : creates >
PQRParser .up.> GHICommand : creates >
PQRParser .up.> JKLCommand : creates >
PQRParser .up.> MNOCommand : creates >
PQRParser .up.> PQRCommand : creates >
}

package instance {
Class ABCInstance
note left: PQRParser = DoctorAppointmentInstance, \n InventoryInstance, \n NurseScheduleInstance, \n StaffInstance, \n StartMenuInstance
ABCInstance .RIGHT.> PQRParser : creates >
ABCInstance .RIGHT.> Command : executes >
}

}

@enduml