@startuml

hide members
hide circle
skinparam classAttributeIconSize 0
package logic{
package command{
Class "{abstract}\nCommand" as Command
package doctorappointment {
Command <|-- ABCCommand
note right: ABCCommand = DoctorAppointmentAddCommand, \n DoctorAppointmentDeleteCommand,\n DoctorAppointmentHelpCommand,\n DoctorAppointmentListCommand, \n DoctorAppointmentReturnCommand
}
package inventory {
Command <|-- DEFCommand
note right: DEFCommand = InventoryAddCommand, \n InventoryDeleteCommand,\n InventoryHelpCommand,\n InventoryListCommand, \n InventoryReturnCommand
}
package nurseschedule {
Command <|-- GHICommand
note right: GHICommand = NurseScheduleAddCommand, \n NurseScheduleDeleteCommand,\n NurseScheduleHelpCommand,\n NurseScheduleListCommand, \n NurseScheduleReturnCommand
}
package patient {
Command <|-- JKLCommand
note right: JKLCommand = PatientAddCommand, \n PatientDeleteCommand, \n PatientFindCommand, \n PatientHelpCommand,\n PatientListCommand, \n PatientReturnCommand
}
package staff {
Command <|-- MNOCommand
note right: MNOCommand = StaffAddCommand, \n StaffDeleteCommand, \n StaffFindCommand, \n StaffHelpCommand,\n StaffListCommand, \n StaffReturnCommand
}
package startmenu {
Command <|-- PQRCommand
note right: PQRCommand = MainExit, \n MainHelp,\n ToDoctorAppointmentInstance,\n ToInventoryInstance, \n ToNurseScheduleInstance, \n ToPatientInstance, \n ToStaffInstance
}
}
package errorchecker{
Class XYZChecker
note right: XYZChecker = DoctorAppointmentChecker, \n InventoryChecker, \n MainChecker, \n NurseScheduleChecker, \n PatientChecker, \n StaffChecker
}

package parser{
Class PQRParser
note right: PQRParser = DoctorAppointmentParser, \n InventoryParser, \n NurseScheduleParser, \n PatientParser, \n StaffParser, \n StartMenuParser
PQRParser .down.> XYZChecker : creates >
PQRParser .up.> ABCCommand : creates >
PQRParser .up.> DEFCommand : creates >
PQRParser .up.> GHICommand : creates >
PQRParser .up.> JKLCommand : creates >
PQRParser .up.> MNOCommand : creates >
PQRParser .up.> PQRCommand : creates >
}

package instance {
Class ABCInstance
note left: PQRParser = DoctorAppointmentInstance, \n InventoryInstance, \n NurseScheduleInstance, \n StaffInstance, \n StartMenuInstance
ABCInstance .RIGHT.> PQRParser : creates >
ABCInstance .RIGHT.> Command : executes >
}

}

@enduml