@startuml

hide members
hide circle

class Duke
class Ui
class ModuleInfo
class HelpGraduation
class TaskManager
class Links
class Storage

Duke -- Ui
Duke --> ModuleInfo
ModuleInfo --> Storage
ModuleInfo -- Ui

Duke --> HelpGraduation
HelpGraduation -- Ui
HelpGraduation --> Storage

Duke --> TaskManager
TaskManager -- Ui
TaskManager --> Storage


Duke --> Links
Links -- Ui
Links --> Storage

@enduml