@startuml

activate ":Duke"
":Duke" -> ":TaskManager"++ : execute

loop true

":TaskManager" -> ":Ui"++ : printTaskManagerMenu
return
":TaskManager" -> ":Ui"++ : readCommand
return

alt Integer.parseInt(command)
    opt command.equals(EXIT_COMMAND)
    ":TaskManager" --> ":Duke"
    end

":TaskManager" -> ":TaskManager"++ : markOrUnmarkTask
":TaskManager" -> ":Ui"++ : printMarkTaskMenu
return
":TaskManager" -> ":TaskManager"++ : getTaskNumber
return
":TaskManager" -> ":MarkOrUnmarkTask"++ : execute

opt TaskManager.taskListIsEmpty(taskTypeNumber)
    ":MarkOrUnmarkTask" -> ":Ui"++ : printTaskListIsEmptyMessage
    return
    ":MarkOrUnmarkTask" --> ":TaskManager"
    end
    ":MarkOrUnmarkTask" -> ":Ui"++ : printSelectTaskNumberToMarkOrUnmark
    return
    alt TOGGLE_TASK_COMMAND
    ":MarkOrUnmarkTask" -> ":MarkOrUnmarkTask"++ : toggleTaskStatus
    return
    else TOGGLE_ASSIGNMENT_COMMAND
    ":MarkOrUnmarkTask" -> ":MarkOrUnmarkTask"++ : toggleTaskStatus
    return
    else TOGGLE_MIDTERM_COMMAND
    ":MarkOrUnmarkTask" -> ":MarkOrUnmarkTask"++ : toggleTaskStatus
    return
    else TOGGLE_FINAL_EXAM_COMMAND
    ":MarkOrUnmarkTask" -> ":MarkOrUnmarkTask"++ : toggleTaskStatus
    return
    else default
    ":MarkOrUnmarkTask" -> ":Ui"++ : printInvalidIntegerMessage
    return
    end

else NumberFormatException
":MarkOrUnmarkTask" -> ":Ui"++ : printInvalidIntegerMessage
return

else IndexOutOfBoundsException
":MarkOrUnmarkTask" -> ":Ui"++ : printInvalidTaskNumberMessage
return
end

return
return

alt
":TaskManager" -> ":Storage"++ : saveAllFiles
return
else IOException
":TaskManager" -> ":Ui"++ : printFilesCouldNotBeSavedMessage
return
end

return

@enduml