@startuml
'https://plantuml.com/sequence-diagram

activate ":HdBuy"
        ":HdBuy" -> ":RemoveCommand": execute()
        activate ":RemoveCommand"
        ":RemoveCommand" -> ":ShortList": removeFrom":ShortList"(index)
        activate ":ShortList"
        ":ShortList" --> ":RemoveCommand": removedUnit
        deactivate ":ShortList"
        alt removedUnit is not null
            ":RemoveCommand" -> ":TextUi": showRemoved":ShortList"Unit(removedUnit)
            activate ":TextUi"
            ":RemoveCommand" <-- ":TextUi"
            deactivate ":TextUi"
        else removedUnit is null
            ":RemoveCommand" -> ":TextUi": showInvalidIndex()
            activate ":TextUi"
            ":RemoveCommand" <-- ":TextUi"
            deactivate ":TextUi"
        end
        ":HdBuy" <-- ":RemoveCommand"
        destroy ":RemoveCommand"

@enduml