@startuml RunningLowSequenceDiagram
'https://plantuml.com/sequence-diagram
!include style.puml

box "Command\n" COMMAND_COLOR_T1
participant ":RunningLowCommand" as RunningLowCommand COMMAND_COLOR
end box

box Food FOOD_COLOR_T1
participant "fridge:Fridge" as Fridge FOOD_COLOR
participant "foodCategory :FoodCategory" as FoodCategory FOOD_COLOR_T3
participant "food:Food" as Food FOOD_COLOR_T4
participant ":MinimumQuantity" as MinimumQuantity FOOD_COLOR_T2
end box

autoactivate on

-> RunningLowCommand: execute()

loop foodCategory in FoodCategory
    RunningLowCommand -> FoodCategory: getFoodCategory()
    return foodCategory

    RunningLowCommand -> Fridge: isRunningOut(foodCategory)
    Fridge -> Fridge: getTotalQuantity()
    loop food in Fridge
        Fridge -> Food: getFoodCategory()
        return foodCategory1
        opt foodCategory1 equals foodCategory
            Fridge -> Food: getQuantity()
            return
        end
    end
    return totalQuantity
    
    Fridge -> MinimumQuantity: getMinimumQuantity()
    return

    alt totalQuantity < MinimumQuantity
        return
    else isStockUp
        RunningLowCommand -> RunningLowCommand: message
        return
    end
end
return
@enduml