@startuml SetLimitSequenceDiagram
'https://plantuml.com/sequence-diagram
!include style.puml

box "Command\n" COMMAND_COLOR_T1
participant ":SetLimitCommand" as SetLimitCommand COMMAND_COLOR
end box

box Food FOOD_COLOR_T1
participant ":MinimumQuantity" as MinimumQuantity FOOD_COLOR_T3
end box

-> SetLimitCommand: execute()
activate SetLimitCommand

SetLimitCommand-> MinimumQuantity: setMinimumQuantity(parameters)
activate MinimumQuantity
return
return

@enduml