@startuml
'https://plantuml.com/sequence-diagram
hide footbox
[-> ":ShortList": getShortListedUnits(inputs)
activate ":ShortList"
opt shortlist not initiated
    ":ShortList" -> ":StorageManager": read()
    activate ":StorageManager"
    loop text input lines in text file
        ":StorageManager" -> ":UnitDecoder": textToUnit(input)
        activate ":UnitDecoder"
        ":StorageManager" <-- ":UnitDecoder": unit
        deactivate ":UnitDecoder"
        opt unit is not null
            ":StorageManager" -> ":ShortList": addToShortList(unit)
            activate ":ShortList"
            ":ShortList" --> ":StorageManager"
            deactivate ":ShortList"
        end
    end
    ":ShortList" <-- ":StorageManager"
    deactivate ":StorageManager"
end
[<-- ":ShortList": units
deactivate ":ShortList"
@enduml