@startuml
'https://plantuml.com/sequence-diagram
!include style.puml

Participant ":XYZCommand" as XYZCommand
Participant ":Storage" as Storage
Participant ":CreditScoreReturnedLoansMap" as CSRLM
Participant ":RecordList" as RecordList

note right of XYZCommand
Add, Remove, and Return Commands
calls the same saveData method,we will
simplify it by grouping them together.
end note

XYZCommand -> Storage : saveData(recordList, (creditScoreReturnedLoansMap))
activate Storage
Storage -> Storage : writeRecordListToSaveFile(recordList)
activate Storage
Loop all records
Storage -> RecordList : getRecordAt()
activate RecordList
RecordList --> Storage : currentRecord : Record
Storage -> RecordList : convertFileFormat()
RecordList --> Storage
deactivate RecordList
RecordList --[Hidden]> Storage
destroy RecordList
end loop

activate Storage
Storage --> Storage
deactivate Storage
Storage -> Storage : writeMapToSaveFile(creditScoreReturnedLoansMap)

activate Storage
Loop Each borrowersName in creditScore
Storage -> CSRLM : getBorrowersNames()
activate CSRLM
CSRLM --> Storage : borrowerName : Set<String>
Storage -> CSRLM : getCreditScoreOf(borrowerName)
CSRLM --> Storage : creditScore : int
deactivate CSRLM
CSRLM --[Hidden]> Storage
destroy CSRLM
end loop
Storage --> Storage
deactivate Storage

@enduml
