@startuml

hide circle
skinparam classAttributeIconSize 0

package Ui {
    class Ui {
        - {static} longHorizontalLine : String
        + {static} readCommand() : String
        + {static} readCommandToInt() : Int
        + {static} printMainMenu()
        + {static} printInvalidInputMessage()
    }
}

@enduml
