@startuml UtilitiesClassDiagram
allow_mixing
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR
skinparam classAttributeIconSize 0

actor User

package Utilities <<Rectangle>> {
    class Ui
    class LoggerHandler
    class Storage
    class Parser
}

package DataFiles <<Rectangle>> {
    file limitsData
    file fridgeData
}

package Food <<Rectangle>> {
    class hiddenFood #FFFFFF
}

package Exception <<Rectangle>> {
    class hiddenException #FFFFFF
}

package Command <<Rectangle>>{
    class hiddenCommand #FFFFFF
}

class Ui {
  -{static} Scanner scanner
  +{static} String getNextLine()
  +{static} void printMessage()
  +{static} void printWelcomeMessage()
  +{static} void printByeMessage()
  +{static} void printExceptionMessage()
}

class LoggerHandler {
  -{static} Logger logger
  +{static} void logInfo(String message)
  +{static} void logInfo(String message, Throwable e)
  +{static} void logWarning(String message)
  +{static} void logWarning(String message, Throwable e)
  +{static} void logSevere(String message)
  +{static} void logSevere(String message, Throwable e)
}

class Storage {
  -{static} String DATA_FILE_PATH
  -{static} String LIMITS_FILE_PATH
  -{static} String DIRECTORY
  -{static} Fridge fridge
  +{static} void load(Fridge fridgeInput)
  +{static} void save(Fridge fridgeInput)
  -{static} void loadFridgeData(Fridge fridgeInput)
  -{static} void checkFridgeDataDirectory()
  -{static} void readFridgeData()
  -{static} void populateFridge(String line)
  -{static} void saveFridgeData()
  -{static} void populateFridgeDataFile()
  -{static} void loadLimitsData()
  -{static} void checkLimitsDirectory()
  -{static} void readLimitsData()
  -{static} void populateFoodCategory()
  -{static} void saveLimitsData()
  -{static} void populateLimitsDataFile()
}

class Parser {
  -{static} int COMMAND_WORD_INDEX
  -{static} int NUMBER_OF_PHRASES
  -{static} Pattern FOOD_DATA_ARGS_FORMAT
  -{static} Pattern REMOVE_ARGS_FORMAT
  -{static} Pattern SET_LIMIT_ARGS_FORMAT
  +{static} Command getCommand(String input)
  +{static} String[] parseInput(String input)
  -{static} Command parseCommand(String[] parsedInput)
  -{static} Command getAddCommand(String description)
  -{static} Command parseFoodDescription(String foodDescription)
  -{static} Command getListCommand(String description)
  -{static} Command getRemoveCommand(String description)
  -{static} Command parseRemoveDescription(String removeDescription)
  -{static} Command getSearchCommand(String description)
  -{static} Command getExpiringCommand()
  -{static} Command getRunningLowCommand()
  -{static} Command getSetLimitCommand(String description)
  -{static} Command parseSetLimitDescription(String description)
  -{static} Command getHelpCommand()
  -{static} Command getClearCommand()
  -{static} Command getByeCommand()
  +{static} int parseIntegerQuantity(String description)
}

' Basic Layout '
LoggerHandler -right[hidden]-> Ui
LoggerHandler -down[hidden]-> Parser
Parser -right[hidden]-> Storage
Ui -down[hidden]-> Storage
Command -right[hidden]-> Exception
Exception -right[hidden]-> Food
Ui -right-> FridgeFriend
Storage -right-> DataFiles
DataFiles -up[hidden]-> FridgeFriend


User --> Ui
Storage .down.> Food
Storage .down.> Exception
Storage ..> Ui
Storage ..> Parser
Parser .down.> Exception
Parser .down.> Command
FridgeFriend --> Storage

'note right of LoggerHandler : Used by all other classes\nfor logging purposes

@enduml