@startuml
'https://plantuml.com/sequence-diagram
!include style.puml
skinparam monochrome true

[-> ":ViewCommand": execute()
activate ":ViewCommand"

alt EXPENSE

    ":ViewCommand" -> ":Ui": printTotalAmountExpense(:RecordList)
    activate ":Ui"
    ":Ui" --> ":ViewCommand"
    deactivate ":Ui"

else LOAN

    ":ViewCommand" -> ":Ui": printTotalAmountLoan(:RecordList)
    activate ":Ui"
    ":Ui" --> ":ViewCommand"
    deactivate ":Ui"

else SAVING

    ":ViewCommand" -> ":Ui": printTotalAmountSaving(:RecordList)
    activate ":Ui"
    ":Ui" --> ":ViewCommand"
    deactivate ":Ui"

end

[<-- ":ViewCommand"
deactivate ":ViewCommand"

@enduml