@startuml
'https://plantuml.com/sequence-diagram
!include style.puml

[-> ":ViewCommand": execute()
activate ":ViewCommand"

note right
    Parameters in execute() are omitted for brevity.
end note

alt EXPENSE

    ":ViewCommand" -> ":Ui": printTotalAmountExpense(:RecordList)
    activate ":Ui"
    ":Ui" --> ":ViewCommand"
    deactivate ":Ui"

else LOAN

    ":ViewCommand" -> ":Ui": printTotalAmountLoan(:RecordList)
    activate ":Ui"
    ":Ui" --> ":ViewCommand"
    deactivate ":Ui"

else SAVING

    ":ViewCommand" -> ":Ui": printTotalAmountSaving(:RecordList)
    activate ":Ui"
    ":Ui" --> ":ViewCommand"
    deactivate ":Ui"

else ALL

    ":ViewCommand" -> ":Ui": printTotalAmountAllType(:RecordList)
    activate ":Ui"
    ":Ui" --> ":ViewCommand"
    deactivate ":Ui"

end

[<-- ":ViewCommand"
deactivate ":ViewCommand"

@enduml