package seedu.hdbuy.api;

import seedu.hdbuy.common.QueryKey;
import seedu.hdbuy.common.Unit;
import seedu.hdbuy.common.exception.EmptyResponseException;

import java.util.HashMap;
import java.util.logging.Logger;

public class ApiRepository {

    /**
     * Gets all units from database matching user's filter criteria.
     * If there are no units retrieved, returns empty map.
     *
     * @param inputs User's filter criteria.
     * @return Map of units, each unit has a unique ID generated by hashcode.
     */
    public static HashMap<Integer, Unit> fetchUnits(HashMap<QueryKey, String> inputs) {
        assert !inputs.isEmpty() : "User did not add any parameters";
        String query = QueryFormatter.formQuery(inputs);
        assert !query.isEmpty() : "Query is empty";
        try {
            return GetRequest.getResponse(query);
        } catch (EmptyResponseException emptyResponseException) {
            Logger.getLogger("ApiRepository").warning(emptyResponseException.getMessage());
            return new HashMap<>();
        }
    }
}
