@startuml
hide circle
skinparam classAttributeIconSize 0

class ShowCustomAliasCommand {
# AliasUi ui
+ void execute()
}
class AddCustomAliasCommand {
# AliasUi ui
- {static} String MESSAGE_SUCCESS
+ void execute()
}
class BlockAlias {
- HashMap<String,String> aliases
+ HashMap<String,String> getAliasHashMap()
+ String[] changeAliasToBlock(String,String)
+ void addAlias(String,String)
+ void deleteAlias(String)
}
class NusMap {
- HashMap<String,Block> map
}
class NusMaze {
- NusMap nusMap
- UiManager ui
- BlockAlias blockAlias
- Storage aliasStorage
}
class DeleteCustomAliasCommand {
# AliasUi ui
- {static} String MESSAGE_SUCCESS
+ void execute()
}
class AliasStorage {
+ void loadAlias(BlockAlias)
+ void overwriteAliasListFile(BlockAlias)
+ void appendToAliasListFile(String)
}
class AliasUi {
+ String[] getAliasInfo()
+ void showCustomAliases(BlockAlias)
+ String getDeleteAliasInfo()
}


"{abstract}\nCommand" <|-- ShowCustomAliasCommand
"{abstract}\nCommand" <|-- AddCustomAliasCommand
"{abstract}\nCommand" <|-- DeleteCustomAliasCommand
"{abstract}\nStorage" <|-- AliasStorage
UiManager <|-- AliasUi

NusMaze --> "**1..***" "{abstract}\nCommand"

DeleteCustomAliasCommand ..> AliasUi
AddCustomAliasCommand ..> AliasUi
ShowCustomAliasCommand ..> AliasUi

NusMaze --> "**1**" BlockAlias
NusMaze --> "**1**" AliasStorage

BlockAlias ..> NusMap

@enduml