@startuml
!include Style.puml

package Command <<Rectangle>> {
    abstract class "{abstract}\nCommand" COMMAND_COLOR {
        # blockAlias: BlockAlias
        # history: History
        # favourite: Favourite
        # dailyRoute: DailyRoute
        # isExit: boolean

        + setData(NusMap, BlockAlias, History, Favourite, DailyRoute): void
        + isExit(): boolean
        + execute(): void
    }

    package routecommand {
        class GoCommand COMMAND_COLOR {
            # ui: RouterUi
        }
    }

    package generalcommand {
        class ByeCommand COMMAND_COLOR {
            # ui: UiManager
        }
        class HelpCommand COMMAND_COLOR {
            # ui: UiManager
        }
    }

    package aliascommand {
        class AddCustomAliasCommand COMMAND_COLOR {
            # ui: AliasUi
        }
        class DeleteCustomAliasCommand COMMAND_COLOR {
            # ui: AliasUi
        }
        class ShowCustomAliasCommand COMMAND_COLOR {
            # ui: AliasUi
        }
    }

    package dailyroutecommand {
        class AddDailyRouteCommand COMMAND_COLOR {
            # ui: DailyRouteUi
        }
        class ShowDailyRouteCommand COMMAND_COLOR {
            # ui: DailyRouteUi
        }
    }

    package favouritecommand {
        class AddFavouriteCommand COMMAND_COLOR {
            # ui: FavouriteUi
        }
        class ShowFavouriteCommand COMMAND_COLOR {
            # ui: FavouriteUi
        }
        class DeleteFavouriteCommand COMMAND_COLOR {
            # ui: FavouriteUi
        }
        class RepeatFavouriteCommand COMMAND_COLOR {
            # ui: FavouriteUi
        }
    }

    package historycommand {
        class ClearHistoryCommand COMMAND_COLOR {
            # ui: HistoryUi
        }
        class RepeatHistoryCommand COMMAND_COLOR {
            # ui: HistoryUi
        }
        class ShowHistoryCommand COMMAND_COLOR {
            # ui: HistoryUi
        }
    }

    package notecommand {
        class AddNoteCommand COMMAND_COLOR {
            # ui: NoteUi
        }
        class DeleteNoteCommand COMMAND_COLOR {
            # ui: NoteUi
        }
        class ListNoteCommand COMMAND_COLOR {
            # ui: NoteUi
        }
    }
}

'ByeCommand -[hidden]down- HelpCommand
'AddDailyRouteCommand -[hidden]down- ShowDailyRouteCommand
dailyroutecommand -[hidden]up- routecommand
notecommand -[hidden]- favouritecommand
historycommand -[hidden]down- aliascommand

"{abstract}\nCommand" <|-up- GoCommand
"{abstract}\nCommand" <|-down- ByeCommand
"{abstract}\nCommand" <|-down- HelpCommand
"{abstract}\nCommand" <|-up- AddCustomAliasCommand
"{abstract}\nCommand" <|-up- DeleteCustomAliasCommand
"{abstract}\nCommand" <|-up- ShowCustomAliasCommand
"{abstract}\nCommand" <|-up- AddDailyRouteCommand
"{abstract}\nCommand" <|-up- ShowDailyRouteCommand
"{abstract}\nCommand" <|-down- AddFavouriteCommand
"{abstract}\nCommand" <|-down- DeleteFavouriteCommand
"{abstract}\nCommand" <|-down- RepeatFavouriteCommand
"{abstract}\nCommand" <|-down- ShowFavouriteCommand
"{abstract}\nCommand" <|-up- ClearHistoryCommand
"{abstract}\nCommand" <|-up- RepeatHistoryCommand
"{abstract}\nCommand" <|-up- ShowHistoryCommand
"{abstract}\nCommand" <|-down- AddNoteCommand
"{abstract}\nCommand" <|-down- DeleteNoteCommand
"{abstract}\nCommand" <|-down- ListNoteCommand

hide methods
show "{abstract}\nCommand" members
hide circle
skinparam classAttributeIconSize 0

@enduml