@startuml
participant Actor
participant GoCommand
participant RouterUi
Actor -> GoCommand : execute
activate GoCommand
GoCommand -> RouterUi: getUserCommandInput
activate RouterUi
RouterUi --> GoCommand:
deactivate RouterUi
create Router
GoCommand -> Router : execute
activate Router
Router -> Router : findShortestRoute
activate Router
Router -> NusMap : resetVisitedFlag
activate NusMap
NusMap -> Block : setAsNotVisited
activate Block
Block --> NusMap
deactivate Block
NusMap --> Router
deactivate NusMap
Router -> NusMap : getBlock
activate NusMap
NusMap --> Router
deactivate NusMap
Router -> NusMap : getBlock
activate NusMap
NusMap --> Router
deactivate NusMap
Router -> Router : bfs
activate Router
Router -> Block : setAsVisited
activate Block
Block --> Router
deactivate Block
Router -> NusMap : getBlock
activate NusMap
NusMap --> Router
deactivate NusMap
Router -> Block : setAsVisited
activate Block
Block --> Router
deactivate Block
Router -> Block : isSameBlock
activate Block
Block --> Router
deactivate Block
Router --> Router
deactivate Router
Router -> NusMap : getBlock
activate NusMap
NusMap --> Router
deactivate NusMap
Router --> Router
deactivate Router
Router -> Router : getRouteAsString
activate Router
Router --> Router
deactivate Router
Router --> GoCommand
deactivate Router
GoCommand -> RouterUi: showMessageWithDivider
activate RouterUi
return
return
@enduml