@startuml
hide circle
skinparam classAttributeIconSize 0

class NoteUi {
+ String[] getNoteInfo()
+ String getBlockInfo()
+ void showNotes(ArrayList<String>)
}
class RouterUi {
+ String[] getRoutingInfo()
+ int getEateryEntry(Block[])
}
class UiManager {
- Scanner in
- PrintStream out
+ String getUserCommandInput()
+ String getUserInput()
+ void showMessage(String)
+ void showMessageWithDivider(String)
}
class HistoryUi {
+ void showHistory(History)
+ int getRepeatEntry()
}
class CommonMessage {
+ {static} String LINE_SEPARATOR
+ {static} String DIVIDER
+ {static} String COMMAND_INPUT_HEADER
+ {static} String INFO_INPUT_HEADER
}
class DailyRouteUi {
+ ArrayList<String> getScheduleInfo()
+ int getDayEntryForAdd(ArrayList<String>)
+ int getDayEntryForShow(ArrayList<String>)
+ void showListOfDays(ArrayList<String>)
+ int getEntryFromUser(ArrayList<String>)
}
class AliasUi {
+ String[] getAliasInfo()
+ void showCustomAliases(BlockAlias)
+ String getDeleteAliasInfo()
}
class FavouriteUi {
+ String[] getFavouriteInfo()
+ void showFavourites(Favourite)
+ int getDeleteIndex()
+ int getRepeatIndex()
}


UiManager <|-- NoteUi
UiManager <|-- RouterUi
UiManager <|-- HistoryUi
UiManager <|-- DailyRouteUi
UiManager <|-- AliasUi
UiManager <|-- FavouriteUi
@enduml