@startuml
'https://plantuml.com/sequence-diagram

autonumber
box AddCanteen

->":AddCanteenCommand" : execute(canteens, ui)
activate ":AddCanteenCommand"

":AddCanteenCommand" -> "ui:Ui" : showAddCanteen()
activate "ui:Ui"
"ui:Ui" --> ":AddCanteenCommand"
deactivate "ui:Ui"

loop !isNameValid
    ":AddCanteenCommand" -> "ui:Ui" : readCommand()
    activate "ui:Ui"
    "ui:Ui" --> ":AddCanteenCommand" : line
    deactivate "ui:Ui"

    alt line == "cancel"
    ":AddCanteenCommand" -> "ui:Ui" : showCanteenNotAdded()
    activate "ui:Ui"
    "ui:Ui" --> ":AddCanteenCommand"
    deactivate "ui:Ui"
    <-- ":AddCanteenCommand"

    else
        loop for canteen in canteens
            alt line == canteen name
            ":AddCanteenCommand" -> "ui:Ui" : showInvalidCanteenPrompt()
            activate "ui:Ui"
            "ui:Ui" --> ":AddCanteenCommand"
            deactivate "ui:Ui"
            end
        end
    end
end

create ":Canteen"
":AddCanteenCommand" -> ":Canteen" : Canteen()
activate ":Canteen"
":Canteen" --> ":AddCanteenCommand"
deactivate ":Canteen"

":AddCanteenCommand" -> "ui:Ui" : showAddCanteenSuccess()
activate "ui:Ui"
"ui:Ui" --> ":AddCanteenCommand"
deactivate "ui:Ui"

":AddCanteenCommand" -> "<<class>> \n:WriteToFile" : saveCanteen()
activate "<<class>> \n:WriteToFile"
"<<class>> \n:WriteToFile" --> ":AddCanteenCommand"
deactivate "<<class>> \n:WriteToFile"

<-- ":AddCanteenCommand"
deactivate ":AddCanteenCommand"
@enduml