@startuml
'https://plantuml.com/sequence-diagram

autonumber
box DeleteStores


->":DeleteStoresCommand": execute(canteens,ui)
activate ":DeleteStoresCommand"
alt canteens.size()>0
    ":DeleteStoresCommand"->":ArrayList<Canteen> canteens":get(canteenIndex)
    activate ":ArrayList<Canteen> canteens"
    ":ArrayList<Canteen> canteens"-->":DeleteStoresCommand":currentCanteen
    deactivate ":ArrayList<Canteen> canteens"
    ":DeleteStoresCommand"->":Ui":showDisplaySelectStores(currentCanteen)
    activate ":Ui"
    ":Ui"-->":DeleteStoresCommand"
    deactivate ":Ui"
    ":DeleteStoresCommand"->":Ui":readCommand()
    activate ":Ui"
    ":Ui"-->":DeleteStoresCommand":line
    deactivate ":Ui"
    alt line.equals("cancel")
        ":DeleteStoresCommand"->":Ui":showStoreNotDeleted()
        activate ":Ui"
        ":Ui"-->":DeleteStoresCommand"
        deactivate ":Ui"
    end
    ":DeleteStoresCommand"->":Canteen":getStore(storeIndex)
    activate ":Canteen"
    ":Canteen"-->":DeleteStoresCommand":store
    deactivate ":Canteen"
    ":DeleteStoresCommand"->":Store":getStoreName()
    activate ":Store"
    ":Store" --> ":DeleteStoresCommand": storeName
    deactivate ":Store"
    ":DeleteStoresCommand"->":Canteen":deleteStore(storeIndex)
    activate ":Canteen"
    ":Canteen"-->":DeleteStoresCommand"
    deactivate ":Canteen"
    ":DeleteStoresCommand"->":Ui":showDeleteStore(storeName)
    activate ":Ui"
    ":Ui"-->":DeleteStoresCommand"
    deactivate ":Ui"
    ":DeleteStoresCommand"->":Storage":save()
    activate ":Storage"
    ":Storage" -->":DeleteStoresCommand"
    deactivate ":Storage"
end
<--":DeleteStoresCommand"
deactivate ":DeleteStoresCommand"
@enduml