@startuml
'https://plantuml.com/sequence-diagram

autonumber
box DisplayCanteensCommand

->":DisplayCanteensCommand" : execute(canteens, ui)
activate ":DisplayCanteensCommand"

":DisplayCanteensCommand" -> "ui:Ui" : showDisplayCanteens(canteens)
activate "ui:Ui"
"ui:Ui" --> ":DisplayCanteensCommand"
deactivate "ui:Ui"

<-- ":DisplayCanteensCommand"
deactivate ":DisplayCanteensCommand"
@enduml

