@startuml
'https://plantuml.com/sequence-diagram

autonumber
box HelpCommand

->":HelpCommand" : execute(canteens, ui)
activate ":HelpCommand"

":HelpCommand" -> "ui:Ui" : showHelpCommand()
activate "ui:Ui"
"ui:Ui" --> ":HelpCommand"
deactivate "ui:Ui"

<-- ":HelpCommand"
deactivate ":HelpCommand"
@enduml

