@startuml
'https://plantuml.com/sequence-diagram

autonumber
box ReadReviews


->":ReadReviewsCommand": execute(canteens,ui)
activate ":ReadReviewsCommand"
":ReadReviewsCommand"->":Store":getReviews()
activate ":Store"
":Store"-->":ReadReviewsCommand":reviews
deactivate ":Store"
opt reviews.size()>0
    ":ReadReviewsCommand"->":Store":getAverageRating()
    activate ":Store"
    ":Store"-->":ReadReviewsCommand":averageRating
    deactivate ":Store"
    ":ReadReviewsCommand"->":Store":getStoreName()
    activate ":Store"
    return storeName
    deactivate ":Store"
    ":ReadReviewsCommand"->":Ui":showReviews(storeName,reviews,averageRating)
    activate ":Ui"
    ":Ui"-->":ReadReviewsCommand"
     deactivate ":Ui"
    <--":ReadReviewsCommand"
end
deactivate ":ReadReviewsCommand"

@enduml