@startuml
hide footbox

actor User
User -> "command:AddDailyRouteCommand" : execute
activate "command:AddDailyRouteCommand"
"command:AddDailyRouteCommand" -> "dailyRoute:DailyRoute" : getValidDays
activate "dailyRoute:DailyRoute"
return
deactivate "dailyRoute:DailyRoute"
"command:AddDailyRouteCommand" -> "ui:DailyRouteUi" : getDayEntryForAdd
activate "ui:DailyRouteUi"
return
deactivate "ui:DailyRouteUi"

"command:AddDailyRouteCommand" -> "ui:DailyRouteUi" : getScheduleInfo
activate "ui:DailyRouteUi"
return
deactivate "ui:DailyRouteUi"

"command:AddDailyRouteCommand" -> "dailyRoute:DailyRoute" : addDailyRoute
activate "dailyRoute:DailyRoute"
"dailyRoute:DailyRoute" --> "command:AddDailyRouteCommand"
deactivate "dailyRoute:DailyRoute"

"command:AddDailyRouteCommand" -> "ui:DailyRouteUi": showMessageWithDivider
activate "ui:DailyRouteUi"
return
deactivate "ui:DailyRouteUi"
"command:AddDailyRouteCommand" --> User
deactivate "command:AddDailyRouteCommand"

@enduml