@startuml
participant Actor
Actor -> AddDailyRouteCommand : execute
activate AddDailyRouteCommand
AddDailyRouteCommand -> DailyRoute : getValidDays
activate DailyRoute
return
deactivate DailyRoute
AddDailyRouteCommand -> DailyRouteUi : getDayEntryForAdd
activate DailyRouteUi
return
deactivate DailyRouteUi

AddDailyRouteCommand -> DailyRouteUi : getScheduleInfo
activate DailyRouteUi
return
deactivate DailyRouteUi

AddDailyRouteCommand -> DailyRoute : addDailyRoute
activate DailyRoute
DailyRoute --> AddDailyRouteCommand
deactivate DailyRoute

AddDailyRouteCommand -> DailyRouteUi: showMessageWithDivider
activate DailyRouteUi
return
deactivate DailyRouteUi
AddDailyRouteCommand --> Actor
deactivate AddDailyRouteCommand
@enduml