@startuml
hide footbox
title Footer removed
actor User
User -> "command:ShowDailyRouteCommand" : execute
activate "command:ShowDailyRouteCommand"
"command:ShowDailyRouteCommand" -> "dailyRoute:DailyRoute" : getSelectableDays
activate "dailyRoute:DailyRoute"
return
deactivate "dailyRoute:DailyRoute"
"command:ShowDailyRouteCommand" -> "ui:DailyRouteUi" : getDayEntryForShow
activate "ui:DailyRouteUi"
return
deactivate "ui:DailyRouteUi"
"command:ShowDailyRouteCommand" -> "dailyRoute:DailyRoute" : getdailyRoute
activate "dailyRoute:DailyRoute"
return
deactivate "dailyRoute:DailyRoute"

create ":Router"
"command:ShowDailyRouteCommand" -> ":Router" : execute
activate ":Router"
":Router" -> ":Router" : findShortestRoute
activate ":Router"
return
return

create ":Router"
"command:ShowDailyRouteCommand" -> ":Router" : execute
activate ":Router"
":Router" -> ":Router" : findShortestRoute
activate ":Router"
return
return
create ":Router"
"command:ShowDailyRouteCommand" -> ":Router" : execute
activate ":Router"
":Router" -> ":Router" : findShortestRoute
activate ":Router"
return
return

"command:ShowDailyRouteCommand" -> "ui:DailyRouteUi": showMessageWithDivider
activate "ui:DailyRouteUi"
return
deactivate "ui:DailyRouteUi"
"command:ShowDailyRouteCommand" --> User
deactivate "command:ShowDailyRouteCommand"
@enduml